apiVersion: v1
kind: Service
metadata:
  name: {{ template "codescene.fullname" . }}
  labels:
    app: {{ template "codescene.fullname" . }}
    chart: {{ template "codescene.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)))}}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    {{- if not (empty .Values.service.httpsPort)}}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.https)))}}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ template "codescene.fullname" . }}
  