image:
  registry: docker.io
  repository: empear/ubuntu-onprem
  tag: 3.5.1
  pullPolicy: IfNotPresent

configMap:
  CODESCENE_DIR: "/data/codescene"
  CODESCENE_DB_PATH: "/data/codescene/codescene"
  CODESCENE_ANALYSIS_RESULTS_ROOT: "/data/codescene/analysis"
  CODESCENE_CLONED_REPOSITORIES_ROOT: "/data/codescene/repos"

service:
  type: LoadBalancer
  httpPort: 80
  targetPort: 3003
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster

ingress:
  enabled: true
  hosts:
  - name: an.fqdn.com
    annotations:
      kubernetes.io/ingress.class: nginx

persistence:
  enabled: true
  codescene:
    accessMode: ReadWriteOnce
    size: 100Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

volumeMounts:
  codescene:
    mountPath: /data/codescene

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30

podAnnotations:
  vault-injection: codescene
